version: '3'

services:
  arccommander_container:
    image: ubuntu:latest
    container_name: arccommander_container
    command: |
      bash -c "apt update && \
             apt install -y wget libicu-dev git && \
             wget https://github.com/nfdi4plants/arcCommander/releases/download/v0.4.0-linux.x64/arc && \
             chmod u+x arc && \
             if ! [ -d "$HOME/bin" ]; then mkdir "$HOME/bin"; fi && \
             mv arc $HOME/bin/ && \
             source ~/.bashrc && \
             arc --version && \
             apt install -y git-lfs && \
             git lfs install &&\
             tail -f /dev/null && \
             cd SampleARC_Proteomics && \
             arc export > metadata.json"
    volumes:
      - D:\Coding\Thesis\Arcdatasets\SampleARC_Proteomics:/arc
  drill:
    image: apache/drill:latest
    ports:
      - '8047:8047'
    stdin_open: true

networks:
  default:
    name: ds2dc_network
    driver: bridge
    driver_opts:
      encrypted: ''
